# Generated by Django 4.2.20 on 2025-03-24 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0008_assignment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Assignment',
        ),
    ]
